-- Generated from generator/demo_specs/aws-philippines-bpo-sla.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-bpo-sla
-- This is the schema that is actually deployed for PH_BPO_SLA.

-- Alerts fire on the bottom tail of SLA Achievement
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_SLA_ACHIEVEMENT) AS T
  FROM RAW.INTERVAL_PERFORMANCE
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_SLA_ACHIEVEMENT <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_SLA_ACHIEVEMENT), 2) AS AVG_SLA_ACHIEVEMENT,
  ROUND(AVG(f.KPI_AVG_RESOLUTION), 2) AS AVG_RESOLUTION,
  ROUND(AVG(f.KPI_ESCALATION_RATE), 2) AS AVG_ESCALATION_RATE
FROM RAW.INTERVAL_PERFORMANCE f
JOIN RAW.CLIENT_CONTRACTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_SLA_ACHIEVEMENT), 2) AS AVG_SLA_ACHIEVEMENT,
  ROUND(AVG(f.KPI_AVG_RESOLUTION), 2) AS AVG_RESOLUTION,
  ROUND(AVG(f.KPI_ESCALATION_RATE), 2) AS AVG_ESCALATION_RATE
FROM RAW.INTERVAL_PERFORMANCE f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_SLA_ACHIEVEMENT) AS KPI_SLA_ACHIEVEMENT, AVG(KPI_AVG_RESOLUTION) AS KPI_AVG_RESOLUTION, AVG(KPI_ESCALATION_RATE) AS KPI_ESCALATION_RATE FROM RAW.INTERVAL_PERFORMANCE),
     en AS (SELECT SUM(KPI_PENALTIES_INCURRED) AS KPI_PENALTIES_INCURRED, SUM(KPI_TICKETS_RESOLVED) AS KPI_TICKETS_RESOLVED, SUM(KPI_ACTIVE_SLAS) AS KPI_ACTIVE_SLAS, SUM(KPI_BREACHES_MTD) AS KPI_BREACHES_MTD FROM RAW.CLIENT_CONTRACTS)
  SELECT 1 AS SORT_ORDER, 'SLA Achievement' AS TITLE, KPI_SLA_ACHIEVEMENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SLA_ACHIEVEMENT), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Penalties Incurred' AS TITLE, KPI_PENALTIES_INCURRED AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_PENALTIES_INCURRED) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Tickets Resolved' AS TITLE, KPI_TICKETS_RESOLVED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_TICKETS_RESOLVED) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active SLAs' AS TITLE, KPI_ACTIVE_SLAS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_SLAS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Breaches (MTD)' AS TITLE, KPI_BREACHES_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_BREACHES_MTD)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Avg Resolution' AS TITLE, KPI_AVG_RESOLUTION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_RESOLUTION), 1) AS DECIMAL(38,1))) || ' ' || 'hrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Escalation Rate' AS TITLE, KPI_ESCALATION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ESCALATION_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
