-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Service Level Optimization & SLA Drift Detection
-- ============================================================================
USE DATABASE SLA_OPERATIONS;
USE SCHEMA ML;

-- ML.ANOMALY_DETECTION: SLA_DRIFT_DETECTOR
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.SLA_DRIFT_DETECTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SLA_TIMESERIES'),
  SERIES_COLNAME => 'CLIENT_METRIC_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'METRIC_VALUE',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.SLA_DRIFT_DETECTOR_RESULTS AS
SELECT * FROM TABLE(ML.SLA_DRIFT_DETECTOR!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SLA_TIMESERIES'), SERIES_COLNAME => 'CLIENT_METRIC_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'METRIC_VALUE'));

-- ML.FORECAST: SLA_BREACH_PREDICTOR
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.SLA_BREACH_PREDICTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SLA_TIMESERIES'),
  SERIES_COLNAME => 'CLIENT_METRIC_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'METRIC_VALUE'
  
);

CREATE OR REPLACE TABLE ML.SLA_BREACH_PREDICTOR_RESULTS AS
SELECT * FROM TABLE(ML.SLA_BREACH_PREDICTOR!FORECAST(FORECASTING_PERIODS => 14));

