-- ============================================================================
-- 99_RESET.SQL — Reset Service Level Optimization & SLA Drift Detection to clean demo state
-- ============================================================================
USE DATABASE SLA_OPERATIONS;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_INTERVALS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_TRIGGER_REMEDIATION SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.SLA_HEALTH_REALTIME REFRESH;
ALTER DYNAMIC TABLE CURATED.PENALTY_EXPOSURE REFRESH;
ALTER DYNAMIC TABLE CURATED.STAFFING_GAP_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE CURATED.SLA_TIMESERIES REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM SLA_OPERATIONS.RAW.INTERVAL_PERFORMANCE → 1200000
-- SELECT COUNT(*) FROM SLA_OPERATIONS.RAW.CLOUDWATCH_ALARMS → 15000
-- SELECT COUNT(DISTINCT CLIENT_METRIC_ID) FROM SLA_OPERATIONS.CURATED.SLA_HEALTH_REALTIME WHERE STATUS = 'DRIFTING' → >=8

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_TRIGGER_REMEDIATION RESUME;
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_INTERVALS RESUME;
